packages:
  - "apps/*"
  - "packages/*"
  - "packages/config/*"

catalog:
  # Base Shared Types & Tooling
  typescript: ^5.9.2
  "@types/node": ^20.17.16
  "@types/react": ~19.2.2

  # Validation / Env
  zod: ^4.4.3
  dotenv: ^16.4.7
  vitest: ^3.2.4

  # Linter / Formatter
  "@biomejs/biome": ^2.2.0
  prettier: ^3.8.1

  # Tailwind CSS V4
  tailwindcss: ^4.2.1
  "@tailwindcss/vite": ^4.2.1

  # React / Expo
  react: 19.2.0
  react-dom: 19.2.0
  react-native: 0.83.2
  expo: ~55.0.4

allowBuilds:
  better-sqlite3: false
  esbuild: true
  lightningcss: true

overrides:
  "@tanstack/query-core": 5.102.6
  isbot: 5.2.1
  systeminformation: 5.33.4
