/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as ClientExpertsRouteImport } from './routes/client/experts'
import { Route as ClientInsightsRouteImport } from './routes/client/insights'
import { Route as ClientMessagesRouteImport } from './routes/client/messages'
import { Route as ClientSessionsRouteImport } from './routes/client/sessions'
import { Route as ExpertIndexRouteImport } from './routes/expert/index'
import { Route as ExpertCalendarRouteImport } from './routes/expert/calendar'
import { Route as ExpertPendingRouteImport } from './routes/expert/pending'
import { Route as ExpertSessionsRouteImport } from './routes/expert/sessions'
import { Route as ExpertsIndexRouteImport } from './routes/experts/index'
import { Route as ExpertsIdRouteImport } from './routes/experts/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientExpertsRoute = ClientExpertsRouteImport.update({
  id: '/client/experts',
  path: '/client/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientInsightsRoute = ClientInsightsRouteImport.update({
  id: '/client/insights',
  path: '/client/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/client/messages',
  path: '/client/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSessionsRoute = ClientSessionsRouteImport.update({
  id: '/client/sessions',
  path: '/client/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertIndexRoute = ExpertIndexRouteImport.update({
  id: '/expert/',
  path: '/expert/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertCalendarRoute = ExpertCalendarRouteImport.update({
  id: '/expert/calendar',
  path: '/expert/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertPendingRoute = ExpertPendingRouteImport.update({
  id: '/expert/pending',
  path: '/expert/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertSessionsRoute = ExpertSessionsRouteImport.update({
  id: '/expert/sessions',
  path: '/expert/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsIndexRoute = ExpertsIndexRouteImport.update({
  id: '/experts/',
  path: '/experts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsIdRoute = ExpertsIdRouteImport.update({
  id: '/experts/$id',
  path: '/experts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/client/experts': typeof ClientExpertsRoute
  '/client/insights': typeof ClientInsightsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/sessions': typeof ClientSessionsRoute
  '/expert/calendar': typeof ExpertCalendarRoute
  '/expert/pending': typeof ExpertPendingRoute
  '/expert/sessions': typeof ExpertSessionsRoute
  '/experts/$id': typeof ExpertsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/experts/': typeof ExpertsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/client/experts': typeof ClientExpertsRoute
  '/client/insights': typeof ClientInsightsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/sessions': typeof ClientSessionsRoute
  '/expert/calendar': typeof ExpertCalendarRoute
  '/expert/pending': typeof ExpertPendingRoute
  '/expert/sessions': typeof ExpertSessionsRoute
  '/experts/$id': typeof ExpertsIdRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/expert': typeof ExpertIndexRoute
  '/experts': typeof ExpertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/client/experts': typeof ClientExpertsRoute
  '/client/insights': typeof ClientInsightsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/sessions': typeof ClientSessionsRoute
  '/expert/calendar': typeof ExpertCalendarRoute
  '/expert/pending': typeof ExpertPendingRoute
  '/expert/sessions': typeof ExpertSessionsRoute
  '/experts/$id': typeof ExpertsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/experts/': typeof ExpertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookings'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/client/experts'
    | '/client/insights'
    | '/client/messages'
    | '/client/sessions'
    | '/expert/calendar'
    | '/expert/pending'
    | '/expert/sessions'
    | '/experts/$id'
    | '/admin/'
    | '/client/'
    | '/expert/'
    | '/experts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookings'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/client/experts'
    | '/client/insights'
    | '/client/messages'
    | '/client/sessions'
    | '/expert/calendar'
    | '/expert/pending'
    | '/expert/sessions'
    | '/experts/$id'
    | '/admin'
    | '/client'
    | '/expert'
    | '/experts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookings'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/client/experts'
    | '/client/insights'
    | '/client/messages'
    | '/client/sessions'
    | '/expert/calendar'
    | '/expert/pending'
    | '/expert/sessions'
    | '/experts/$id'
    | '/admin/'
    | '/client/'
    | '/expert/'
    | '/experts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingsRoute: typeof BookingsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ClientExpertsRoute: typeof ClientExpertsRoute
  ClientInsightsRoute: typeof ClientInsightsRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientSessionsRoute: typeof ClientSessionsRoute
  ExpertCalendarRoute: typeof ExpertCalendarRoute
  ExpertPendingRoute: typeof ExpertPendingRoute
  ExpertSessionsRoute: typeof ExpertSessionsRoute
  ExpertsIdRoute: typeof ExpertsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ExpertIndexRoute: typeof ExpertIndexRoute
  ExpertsIndexRoute: typeof ExpertsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/experts': {
      id: '/client/experts'
      path: '/client/experts'
      fullPath: '/client/experts'
      preLoaderRoute: typeof ClientExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/insights': {
      id: '/client/insights'
      path: '/client/insights'
      fullPath: '/client/insights'
      preLoaderRoute: typeof ClientInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/messages': {
      id: '/client/messages'
      path: '/client/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/sessions': {
      id: '/client/sessions'
      path: '/client/sessions'
      fullPath: '/client/sessions'
      preLoaderRoute: typeof ClientSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/': {
      id: '/expert/'
      path: '/expert'
      fullPath: '/expert/'
      preLoaderRoute: typeof ExpertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/calendar': {
      id: '/expert/calendar'
      path: '/expert/calendar'
      fullPath: '/expert/calendar'
      preLoaderRoute: typeof ExpertCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/pending': {
      id: '/expert/pending'
      path: '/expert/pending'
      fullPath: '/expert/pending'
      preLoaderRoute: typeof ExpertPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/sessions': {
      id: '/expert/sessions'
      path: '/expert/sessions'
      fullPath: '/expert/sessions'
      preLoaderRoute: typeof ExpertSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/': {
      id: '/experts/'
      path: '/experts'
      fullPath: '/experts/'
      preLoaderRoute: typeof ExpertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/$id': {
      id: '/experts/$id'
      path: '/experts/$id'
      fullPath: '/experts/$id'
      preLoaderRoute: typeof ExpertsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingsRoute: BookingsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ClientExpertsRoute: ClientExpertsRoute,
  ClientInsightsRoute: ClientInsightsRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientSessionsRoute: ClientSessionsRoute,
  ExpertCalendarRoute: ExpertCalendarRoute,
  ExpertPendingRoute: ExpertPendingRoute,
  ExpertSessionsRoute: ExpertSessionsRoute,
  ExpertsIdRoute: ExpertsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClientIndexRoute: ClientIndexRoute,
  ExpertIndexRoute: ExpertIndexRoute,
  ExpertsIndexRoute: ExpertsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
